### ISSUE TITLE
[🐞]: missing textures in waystone (perhaps due to fresh waystone textures)

### ISSUE THREAD

**Issue by Newguy225** [MehVahdJukaar/StoneZone#129]
### Code of Conduct

- [x] Always check you are using the latest version of the mods and its dependencies
- [x] Ensure the version of EveryCompat & Moonlight Lib are up to date
- [x] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [x] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [x] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version - Loader (DO NOT FORGET TO SELECT THE CORRECT VERSION)

1.20.1 - FORGE

### StoneZone Version

stonezone-1.20-2.8.15.jar

### EveryCompat Version

everycomp-1.20-2.8.15-forge.jar

### Moonlight Lib Version

moonlight-1.20-2.15.6-forge.jar

### Issue with mods

waystones 

### Issue Detail

the models in the creative menu do not register properly i believe either you or mehvahdjukaar found out the cause for this in wood good, that being that some code was missing to render it properly in the creative menu, but textures are also missing when you place the waystones, though it could potentially be fresh waystone textures breaking it

### OPTIONAL: Latest.log | Crash-report Attachment

no crash

<img width="672" height="1070" alt="Image" src="https://github.com/user-attachments/assets/ff87a069-b46a-4f8a-b565-5b9524007ca2" />

<img width="578" height="310" alt="Image" src="https://github.com/user-attachments/assets/cda6b19a-7a39-478f-a1af-1aab445c675f" />

### OPTIONAL: To Produce

look at it

**Comment by Xelbayria** [comment]
that's strange. Waystones must be recently updated.

**Comment by Xelbayria** [comment]
## FIXED in v2.9.0

---

it must be the block textures wasn't being generated for the waystones. it's rendering correct so it has the shape but don't have the textures. 

EDIT: I'll leave this open until you can confirm it's fixed in v2.9.0

**Comment by Xelbayria** [comment]
can you get me the link to that mod's curseforge page? I think that may be the wrong mod to use. 

StoneZone support this [Waystones](https://www.curseforge.com/minecraft/mc-mods/waystones). but it doesn't support other waystones mod except one for FABRIC mod called "Wraith Waystones"

**Comment by Newguy225** [comment]
@Xelbayria ok im coming to find out i just didnt have waystones installed, but the weird thing is for other mods i do have installed textures still dont work (there is like an absurd number of missing textures, way too many to name in a single post) i.e chipped

also there is no "v2.9.0" on curseforge for me and i even have it set to show me versions that are incompatible, i have the most recent version installed.

**Comment by Newguy225** [comment]
by the way alot of the missing textures are from several different mods

**Comment by Newguy225** [comment]
its already mentioned here in another post but ill bring it up here aswell since i cant find any fixes

**Comment by Newguy225** [comment]
and just as another important detail im using the most recent version of all mods

**Comment by Xelbayria** [comment]
> [@Xelbayria](https://github.com/Xelbayria) ok im coming to find out i just didnt have waystones installed, but the weird thing is for other mods i do have installed textures still dont work (there is like an absurd number of missing textures, way too many to name in a single post) i.e chipped
> 
> also there is no "v2.9.0" on curseforge for me and i even have it set to show me versions that are incompatible, i have the most recent version installed.

that's because it's a NOTICE (v2.9.0) is WIP because i have other bugs to fix. 

the missing texture / flat texture (not a block, just flat) bug is already fixed in v2.9.0, too. 

`ok im coming to find out i just didnt have waystones installed` 

I think that mod has the same mod_id as the waystones (the link i provided above). 

---

> by the way alot of the missing textures are from several different mods

Is this related to Waystone? There are cases where StoneZone was trying to find a texture for a StoneType from Stone Mods but can't find it because the filename are different. if that's the case, then I'll need these Stone Mods. and also Latest.log so i can determine which StoneTypes for Waystone are missing textures

**Comment by Newguy225** [comment]
@Xelbayria partially related to waystone as in waystone textures are also missing but textures for several other mods are missing (example chipped blocks for twilight forests deadrock)

**Comment by Newguy225** [comment]
also as for ur concern on which mods it is for me its pretty much every supported stone i can show you the stonezone thing in creative mode its like 70% missing textures

**Comment by Newguy225** [comment]
seems the new update fixed it @Xelbayria but as a headsup youve got a SINGLE missing texture from the mazestone bridge support 

<img width="955" height="1286" alt="Image" src="https://github.com/user-attachments/assets/8491414f-d496-471b-8e29-1babbf1c4afd" />

**Comment by Newguy225** [comment]
also waystone textures are still missing for me so im starting to think its probably fresh waystone textures messing with things

**Comment by Newguy225** [comment]
@Xelbayria ok ive just confirmed its a conflict with the resource pack "fresh waystones texture" as every waystone texture works without it, ill link that here if you wanna add compatibility

**Comment by Newguy225** [comment]
https://www.curseforge.com/minecraft/texture-packs/fresh-waystones-texture

**Comment by Newguy225** [comment]
sorry to spam this thread, since ive found the problem ill close this thread and open it in another issue
