### ISSUE TITLE
[🐞]: Undetected Stone Types

### ISSUE THREAD

**Issue by VoidLeech** [MehVahdJukaar/StoneZone#17]
### Code of Conduct

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Ensure the version of EveryCompat & Moonlight Lib are up to date
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version - Loader (DO NOT FORGET TO SELECT THE CORRECT VERSION)

1.20.1 - FORGE

### StoneZone Version

stonezone-1.20-2.7.2

### Moonlight Lib Version

moonlight-1.20-2.13.41

### Issue with mods

Create 0.5.1j (create)
Enlightend 5.0.14 (enlightened_end)
Aether Redux 2.0.18 (aether_redux)
Deep Aether 1.0.4 (deep_aether)
Deeper and Darker 1.3.3 (deeperdarker)
Aetherworks Refracted 1.1.2 (aetherworks)
Alex's Caves 2.0.2 (alexscaves)
Rubinated Nether 1.3.0.D (rubinated_nether)

### Issue Detail

The following stone types do not generate compat blocks from furniture mods. I recall note block sound mattering for woodgood so I've listed that here as well.
- create
  - [X] create:limestone (bass drum)
  - [X] create:asurine (bass drum)
  - [X] create:crimsite (bass drum)
  - [X] create:ochrum (bass drum)
  - [X] create:veridium (bass drum)
  - [X] create:scoria (bass drum)
  - [X] create:scorchia (bass drum)

- enlightened_end
  - [X] enlightened_end:void_shale (bass drum)

- aether_redux
  - [X] aether_redux:sentrite (harp)
  - [X] aether_redux:driftshale (bass drum)
  - [X] aether_redux:divinite (harp)

- deep_aether
  - [X] deep_aether:clorite (bass drum)
  - [X] deep_aether:raw_clorite (bass drum)

- alexscaves
  - [X] alexscaves:radrock (harp)
  - [X] alexscaves:abyssmarine (harp)
  - [X] alexscaves:limestone (harp)
  - [X] alexscaves:guanostone (harp)
  - [X] alexscaves:coprolith (harp)
  - [X] alexscaves:galena (harp) 

- aetherworks
  - [X] aetherworks:suevite (harp)

- rubinated_nether
  - [X] rubinated_nether:altar_stone (bass drum)

- deeperdarker
  - [X] deeperdarker:sculk_stone (bass drum)

**Comment by MehVahdJukaar** [comment]
partially duplicate of https://github.com/MehVahdJukaar/StoneZone/issues/16?
Also same question as I said there

**Comment by VoidLeech** [comment]
Oh whoops yeah there’s some overlap. I’ve already listed the note block sounds (and some indeed do not have bass drum)

From what I understand from Xelbayria they also currently need to have a type_bricks (where type is a single word) to be detected, which isn’t the case for these, but they are all stones that also already have some basic variants, which is why I report them as undetected.

**Comment by Xelbayria** [comment]
I see they have different sounds: HARP. and Most have BASS_DRUM. do they have bricks block?

**Comment by VoidLeech** [comment]
From the ones I list above, the following do have a bricks block, but they have either harp or two word names xd:
- aether_redux:sentrite (aether_redux:sentrite_bricks)
- rubinated_nether:altar_stone (rubinated_nether:altar_stone_bricks)
- aetherworks:suevite (aetherworks:suevite_bricks)
- deeperdarker:sculk_stone (deeperdarker:sculk_stone_bricks)
- enlightened_end:void_shale (enlightened_end:void_shale_bricks)
- alexscaves:galena (alexscaves:galena_bricks)
- alexscaves:radrock (alexscaves:radrock_bricks)
- alexscaves:abyssmarine (alexscaves:abyssmarine_bricks)
- alexscaves:guanostone (alexscaves:guanostone_bricks)

**Comment by MehVahdJukaar** [comment]
Two word names separated by _ we will have to add manually. Stuff with (arguably) incorrect note block sounds it's obviously not our issue

**Comment by Xelbayria** [comment]
I am going to work on that tonight.

**Comment by VoidLeech** [comment]
Hmm I see. Think it’ll be harder to convince devs they have the wrong sound here than with wood. Have you considered some api so a user/(developer that isn’t the dev of the mod with the wrong sound) can opt-in a stone anyway?

**Comment by Xelbayria** [comment]
I can manually add these stoneTypes to StoneZone. There are some undetected woodTypes for EveryComp. same method.   Even The woodType have the correct sound. 

The API is already setup in StoneZone. but for EveryCompat, it's in Moonlight.

**Comment by MehVahdJukaar** [comment]
Thing is if they are set up wrong it's factually their bug no? API is for Devs, basically by definition. And mod can't depend on configs so no

**Comment by Xelbayria** [comment]
☝🏻  He's not wrong, tho. They should set these stone to have the correct sound. wood is no different. it's not a lot of works to fix a simple bug, the incorrect sound for stoneTypes

**Comment by Xelbayria** [comment]
> From the ones I list above, the following do have a bricks block, but they have either harp or two word names xd:
> 
>     * [x]  aether_redux:sentrite (aether_redux:sentrite_bricks)
> 
>     * [x]  rubinated_nether:altar_stone (rubinated_nether:altar_stone_bricks)
> 
>     * [x]  aetherworks:suevite (aetherworks:suevite_bricks)
> 
>     * [x]  deeperdarker:sculk_stone (deeperdarker:sculk_stone_bricks)
> 
>     * [x]  enlightened_end:void_shale (enlightened_end:void_shale_bricks)
> 
>     * [x]  alexscaves:galena (alexscaves:galena_bricks)
> 
>     * [x]  alexscaves:radrock (alexscaves:radrock_bricks)
> 
>     * [x]  alexscaves:abyssmarine (alexscaves:abyssmarine_bricks)
> 
>     * [x]  alexscaves:guanostone (alexscaves:guanostone_bricks)

@VoidLeech i've finished add the stonetypes above

is that all?

**Comment by VoidLeech** [comment]
> is that all?

The original issue lists more stone types that do have BASS_DRUM, but not a type_bricks (which I don’t think should be disqualifying considering andesite and such don’t have bricks either)

**Comment by Xelbayria** [comment]
Done. Let me know if DEV won't fix the problem on their side.

**Comment by Xelbayria** [comment]
## ADDED in v2.7.3

**Comment by VoidLeech** [comment]
Is the use of `simpleFinder` in 5d44d504b66e7243a57a9c4ef82ea9e7a69586bc safe? Since simpleFinder adds a bricks child when the ones added in this commit don't have bricks. 
I'll let the devs know and keep you updated. I know Aether Redux isn't maintained for 1.20.1 anymore but it might still get changed for 1.21.1.

**Comment by Xelbayria** [comment]
It's safe. That's because simpleFinder is using `StoneType.Finder.simple()` to find stone and bricks... You can check the log. If there are error logging for finding the bricks. 

I can improve the method.
