### ISSUE TITLE
[🗃]: Create compat incomplete

### ISSUE THREAD

**Issue by VoidLeech** [MehVahdJukaar/StoneZone#2]
### Version - Loader

1.20.1 - FORGE

### Supported Mod Version

0.5.1j

### Supported mod's Curseforge

https://www.curseforge.com/minecraft/mc-mods/create

### Details

![2024-12-11_18 43 17](https://github.com/user-attachments/assets/17e2be32-910a-41ce-94db-41d9c91a7fb0)
Looking at the available blocks to set via setblock, only three variants are available:
cut_TYPE
cut_TYPE_slab
cut_TYPE_stairs
Meanwhile, Create also has:
cut_TYPE_wall
polished_cut_TYPE
polished_cut_TYPE_slab
polished_cut_TYPE_stairs
polished_cut_TYPE_wall
cut_TYPE_bricks
cut_TYPE_brick_slab
cut_TYPE_brick_stairs
cut_TYPE_brick_wall
small_TYPE_bricks
small_TYPE_brick_slab
small_TYPE_brick_stairs
small_TYPE_brick_wall
layered_TYPE
TYPE_pillar

**Comment by Xelbayria** [comment]
Thanks for the report. 

Can you check which stone mod have the polish stuff. I'll need to see if it's possible to support Polish blocks.

**Comment by VoidLeech** [comment]
All the ids I listed are stone variants that Create adds. See:
![image](https://github.com/user-attachments/assets/c23184d9-9601-46a0-a603-a57136b3a6d4)

Setblock lists no blocks under the "stonezone" id. As shown in the initial report they're registered under the everycomp id.
![image](https://github.com/user-attachments/assets/841529a4-c875-42e9-b561-96fc349823a0)
There'd be suggested blocks popping up if they were registered under stonezone. Compare with: 
![image](https://github.com/user-attachments/assets/30cef77c-3eb2-4238-bbab-b30b44d0985d)
If they're supposed to show up under stonezone I guess that's another bug (:

**Comment by Xelbayria** [comment]
FYI, 

STONE MOD (just like wood mod that add types, example: Biomes O' Plenty)

FURNITURE MOD are: Create, twigs, Stoneworks, or BUilding But Better. 

I cannot find a good stone mod to see if i can include polished stones

**Comment by Xelbayria** [comment]
one more thing: 

> Setblock lists no blocks under the "stonezone" id. As shown in the initial report they're registered under the everycomp id.

Yea I thought v2.7.0 would have it under stonezone. it's fixed in v2.7.1

**Comment by VoidLeech** [comment]
> I cannot find a good stone mod to see if i can include polished stones

Uhh wait so what do you need exactly? 
- [X] STONE MOD
- [ ] Adds a polished_TYPE? This is a vanilla variant so I don't expect you to add it. (Create's own TYPES---limestone, asurine, veridium, crimsite, ochrum, scoria & scorchia---don't have these either but still have the polished_cut_TYPE that Create adds)
- [ ] Adds a polished_cut_TYPE? I don't think there is a single mod that adds a polished_cut_TYPE besides Create, tbh. 
- [ ] Adds something else?

**Comment by Xelbayria** [comment]
I took another look at the **Create**, I don't know it has StoneTypes. I am going to run a test with Twigs to see if it can be used with Create's StoneType. 

---
(just so you know these have stoneTypes that I can use to test, if you use a different stone mod aside below. that's what I want to know) 
**STONE MOD:** 
- Create
- Strata
- TerraFirmaCraft

**Create not supported blocks:** 
- polished_type
- polished_cut
- cut_type_wall (forgot to add this)

anything else I missed?

**Comment by VoidLeech** [comment]
>  if you use a different stone mod aside below. that's what I want to know

Ah, like that, okay yeah I see. There's actually quite a bunch haha, just off the top of my head:
- Quark
- Undergarden
- Aether
- Deep Aether
I think there might be some stones that are undetected (or things that I wouldn't personally classify as stone getting detected) as well but I'd have to check.

**These are the Create stone variant blocks that stone zone does not support**, where TYPE should be a StoneType
- cut_TYPE_wall
- polished_cut_TYPE
- polished_cut_TYPE_slab
- polished_cut_TYPE_stairs
- polished_cut_TYPE_wall
- cut_TYPE_bricks
- cut_TYPE_brick_slab
- cut_TYPE_brick_stairs
- cut_TYPE_brick_wall
- small_TYPE_bricks
- small_TYPE_brick_slab
- small_TYPE_brick_stairs
- small_TYPE_brick_wall
- layered_TYPE
- TYPE_pillar

**Comment by Xelbayria** [comment]
wow. lot of blocks from Create :O

**Comment by Xelbayria** [comment]
@VoidLeech 

> I am going to run a test with Twigs to see if it can be used with Create's StoneType.

There are no problem with Create's StoneType. it got detected and supported with other supported mods like Building But Better

**Comment by Xelbayria** [comment]
## Enhanced in v2.7.1

**Comment by VoidLeech** [comment]
> There are no problem with Create's StoneType. it got detected and supported with other supported mods like Building But Better

That’s good to know! And awesome stuff with the enhancements and fixes so quick already; I am beyond excited for this mod.
